const String blob1 = 'asset/images/blob (1).svg';
const String blob2 = 'asset/images/blob (2).svg';
const String blob3 = 'asset/images/blob (3).svg';
const String blob4 = 'asset/images/blob.svg';
const String overlay = 'asset/images/Asset 11a.svg';
const String hmm1 = 'asset/images/h.png';
const String hmm2 = 'asset/images/h1.png';
const String hmm3 = 'asset/images/h2.png';
const String test = 'asset/images/test.jpg';
